project:
  type: website

website:
  title: "Charting Waterloo Region"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/greg-berberich/
      - icon: github
        href: https://github.com/gpberber/chartingwaterlooregion
format:
  html:
    theme: 
      - simply
      - custom.scss
    css: styles.css
    grid: 
      body-width: 1000px

editor: visual

