project:
  type: website

website:
  title: "Deadicated to Data"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/greg-berberich/
      - icon: github
        href: https://github.com/gpberber/deadicated-to-data
format:
  html:
    theme: 
      - simply
      - custom.scss
    css: styles.css

editor: visual

