project:
  type: website

website:
  title: "Deadicated to Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: lux
    css: styles.css

editor: visual

